# for *-php-fpm and *-hhvm base image
app:
    build: ./
    volumes:
        - ./:/var/www/html/
    external_links:
        - backend_db_1:db
        - backend_redis_1:redis
    environment:
        ENABLE_ENV_FILE: 1
        API_TOKEN: 12b03e4773e40d8cc83c892990d7e449b4fe184d

nginx:
    build: ./nginx
    ports:
        - "8086:80"
    links:
        - app
    volumes_from:
        - app


